### PR TITLE
No token for public resources

### PR DESCRIPTION
**Pull request by mrm**

### CODE REVIEW

**Comment by mrm** [comment]
It would probably be better to remove the current login method and create a Login resource?

Then the user of the library could use that to can handle the login inside the AccountStore implementation for example.

**Comment by ricogoh** [comment]
To login have 3 inputs **email**, **password** and **totp** (optional)

```
$response = $this->postUrl('login', [
                'json' => [
                    'email'    => $this->accountStore->getUsername(),
                    'password' => $this->accountStore->getPassword(),
                    'totp'    => $this->accountStore->getTotp()
                ]
            ]);
```

To login with OTP might need 2 inputs which are **totp** and **auth_token**

```
$response = $this->postUrl('totp', [
                'json' => [
                    'auth_token'    => $this->accountStore->getAuthToken(),
                    'totp'          => $this->accountStore->getTotp()
                ]
            ]);
```

**Comment by mrm** [comment]
I'm not sure what the API will exactly return with 2FA as I can't enable it. But might want to change the login function to return the response instead of throwing an exception if the response code isn't 200?

**Comment by dakra** [comment]
Why can't you enable it? It's already implemented in the cp, go to your user settings there.

But just to clarify the undocumented workflow a bit:
POST to `/login` with email,password,totp will log you in directly when you have 2fa enabled.

But since we don't always want to show 3 input fields (at least not in the cp) and don't know beforehand if the user has 2fa activated or not, you just submit email, password.
If that's enough, you're logged in. if not, you get a message and a temporary auth token back that's only valid to post the 'totp' to `/totp` and then you're logged in.

Hope that makes sense :)

**Comment by mrm** [comment]
@ricogoh you can now either use the `totp` field for login right away, or login and check yourself and show a second page in case the user requires the extra `totp` field (you probably want to use your own `MemoryAccountStore` implementation in that case).

Also note that the `ApiException` is now in a different namespace.

**Comment by ricogoh** [comment]
Thanks!  Will check it...

**Pull request merged**
